#!/usr/bin/env bash
#
# bootstrap.sh — one-command setup to make mise's core `python` tool install a
# given version from OUR prebuilt release instead of compiling it from source.
#
# WHAT IT DOES (run this AFTER a `cpython-v<version>` release exists):
#   1. resolves the release asset for THIS machine's arch + its published sha256,
#   2. writes ~/.config/mise/python-build-defs/<version> (a "copy" definition),
#   3. adds PYTHON_BUILD_DEFINITIONS to ~/.config/mise/config.toml [env] (idempotent,
#      backs up first),
#   4. tells you to run `mise install python@<version>`.
#
# After this, `python = "<version>"` in mise config and a `.python-version` of
# <version> resolve to the prebuilt — ONE `python` tool, alongside the precompiled
# 3.11/3.14 that mise still fetches natively.
#
# USAGE:
#   PYBUILDS_REPO=<owner>/python-builds ./bootstrap.sh [<python_version>]
#   # default version: 3.6.15
#
set -euo pipefail

REPO="${PYBUILDS_REPO:-<OWNER>/python-builds}"
VER="${1:-3.6.15}"
DEFS_DIR="${PYTHON_BUILD_DEFINITIONS_DIR:-${HOME}/.config/mise/python-build-defs}"
CONFIG_TOML="${MISE_CONFIG_TOML:-${HOME}/.config/mise/config.toml}"
TAG="cpython-v${VER}"

if [[ "${REPO}" == "<OWNER>/python-builds" ]]; then
  echo "ERROR: set PYBUILDS_REPO=<your-owner>/python-builds (or edit REPO at the top)." >&2
  exit 2
fi

# --- resolve the target triple for this machine ------------------------------
os="$(uname -s)"; arch="$(uname -m)"
case "${os}-${arch}" in
  Darwin-arm64)  triple="aarch64-apple-darwin" ;;
  Darwin-x86_64) triple="x86_64-apple-darwin" ;;
  *) echo "ERROR: unsupported platform '${os}-${arch}' (no published build for it)." >&2; exit 3 ;;
esac
ASSET="cpython-${VER}-${triple}.tar.gz"
BASE="https://github.com/${REPO}/releases/download/${TAG}"
URL="${BASE}/${ASSET}"
SHA_URL="${BASE}/${ASSET}.sha256"

# --- fetch the sha256 sidecar (fails clearly if the release/asset is missing) -
echo "==> resolving ${ASSET} from ${REPO}@${TAG}"
if ! sha_line="$(curl -fsSL "${SHA_URL}")"; then
  echo "ERROR: could not fetch ${SHA_URL}" >&2
  echo "       Does the '${TAG}' release exist and include the .sha256 sidecar for ${triple}?" >&2
  exit 4
fi
SHA="$(printf '%s\n' "${sha_line}" | awk '{print $1}')"
[[ -n "${SHA}" ]] || { echo "ERROR: empty sha256 parsed from ${SHA_URL}" >&2; exit 4; }

# --- write the python-build definition (filename MUST equal the version) ------
mkdir -p "${DEFS_DIR}"
DEF="${DEFS_DIR}/${VER}"
cat > "${DEF}" <<EOF
# Auto-generated by python-builds/bootstrap.sh — makes mise's core \`python\` tool
# install ${VER} from a prebuilt release instead of compiling it.
# "copy" build mode = extract the tarball and copy it in as-is (no build step).
install_package "cpython-${VER}-custom" "${URL}#${SHA}" "copy"
EOF
echo "==> wrote ${DEF}"

# --- ensure PYTHON_BUILD_DEFINITIONS is set in mise config [env] (idempotent) --
if [[ -f "${CONFIG_TOML}" ]] && grep -q 'PYTHON_BUILD_DEFINITIONS' "${CONFIG_TOML}"; then
  echo "==> PYTHON_BUILD_DEFINITIONS already set in ${CONFIG_TOML}; leaving it alone"
else
  [[ -f "${CONFIG_TOML}" ]] && cp "${CONFIG_TOML}" "${CONFIG_TOML}.bak"
  if [[ -f "${CONFIG_TOML}" ]] && grep -qE '^\[env\]' "${CONFIG_TOML}"; then
    # insert the key immediately under the existing [env] table header
    awk -v v="${DEFS_DIR}" '
      /^\[env\]/ && !ins { print; print "PYTHON_BUILD_DEFINITIONS = \"" v "\""; ins=1; next }
      { print }
    ' "${CONFIG_TOML}" > "${CONFIG_TOML}.tmp" && mv "${CONFIG_TOML}.tmp" "${CONFIG_TOML}"
  else
    # no [env] table yet — append one at the end
    printf '\n[env]\nPYTHON_BUILD_DEFINITIONS = "%s"\n' "${DEFS_DIR}" >> "${CONFIG_TOML}"
  fi
  echo "==> added PYTHON_BUILD_DEFINITIONS to ${CONFIG_TOML}${CONFIG_TOML:+ (backup: ${CONFIG_TOML}.bak)}"
fi

cat <<EOF

Done. Next:
  mise install python@${VER}      # downloads the prebuilt (no compile)

Then use it anywhere:
  python = "${VER}"               # in a mise config, or
  echo ${VER} > .python-version   # per-project

3.11 / 3.14 keep using mise's fast precompiled downloads — this only affects ${VER}.
EOF
